package Rumahsakit;

import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;

public class ManagePasien extends javax.swing.JDialog {
    Connection koneksi;
    String action, idpasien;
    
    public ManagePasien(java.awt.Frame parent, boolean modal, String act, String id_pasien) {
        super(parent, modal);
        initComponents();
        koneksi = DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "rumahsakit");
        action = act;
        idpasien = id_pasien;
        
        if (act.equals("add")){
            ShowForm(act, null);
        } else if (act.equals("edit")){
            ShowForm(act, id_pasien);
            tb_nomedrec.setEnabled(false);
        }
    }
    
    void ShowForm(String act, String nomedrec){
        if (act.equals("edit")){
            try{
                Statement stmt = koneksi.createStatement();
                String query = "SELECT * FROM pasien WHERE nomedrec = '"+nomedrec+"'";
                ResultSet rs = stmt.executeQuery(query);
                rs.first();
                tb_nomedrec.setText(rs.getString("nomedrec"));
                tb_nama.setText(rs.getString("nama_pasien"));
                tb_tempat.setText(rs.getString("tempat_lahir"));
                tb_tanggal.setDate(rs.getDate("tgl_lahir"));
                tb_alamat.setText(rs.getString("alamat"));
                tb_kota.setText(rs.getString("kota"));
                tb_telp.setText(rs.getString("telepon"));
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan di Query!");
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        tb_nomedrec = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tb_tempat = new javax.swing.JTextField();
        tb_nama = new javax.swing.JTextField();
        tb_alamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmdSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tb_telp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tb_kota = new javax.swing.JTextField();
        tb_tanggal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setText("Nama Pasien");

        jLabel8.setText("Tempat Lahir");

        tb_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_alamatActionPerformed(evt);
            }
        });

        jLabel3.setText("Alamat");

        jLabel2.setText("Tanggal Lahir");

        lblJudul.setFont(new java.awt.Font("Big Winks", 1, 36)); // NOI18N
        lblJudul.setText("Manage Data Pasien");

        jLabel1.setText("ID Pasien");

        cmdSubmit.setLabel("SAVE");
        cmdSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSubmitActionPerformed(evt);
            }
        });

        jLabel4.setText("Kota");

        tb_telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_telpActionPerformed(evt);
            }
        });

        jLabel5.setText("No. Telepon");

        tb_kota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_kotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJudul)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cmdSubmit)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tb_tanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addComponent(tb_tempat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tb_nama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tb_nomedrec, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(66, 66, 66)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tb_kota, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(tb_telp)
                                .addComponent(tb_alamat)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tb_nomedrec, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tb_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tb_tempat, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tb_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tb_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tb_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tb_tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdSubmit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_alamatActionPerformed

    private void cmdSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSubmitActionPerformed
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat format = new SimpleDateFormat(tampilan);
        RumahSakitApp rsa = new RumahSakitApp();
        
        String nomedrec = tb_nomedrec.getText();
        String nama = tb_nama.getText();
        String tempat_lahir = tb_tempat.getText();
        String tgl_lahir = String.valueOf(format.format(tb_tanggal.getDate()));
        String alamat = tb_alamat.getText();
        String kota = tb_kota.getText();
        String telp = tb_telp.getText();

        if(action.equals("add")){
            try{
                Statement stmt = koneksi.createStatement();
                String query = "INSERT INTO pasien(nomedrec, nama_pasien, tempat_lahir, tgl_lahir, alamat, "
                + "kota, telepon)"
                + "VALUE('"+nomedrec+"','"+nama+"','"+tempat_lahir+"','"
                + tgl_lahir+"','"+alamat+"','"+kota+"','"
                + telp+"')";
                int berhasil = stmt.executeUpdate(query);
                if(berhasil == 1){
                    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan!");
                } else {
                    JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan!");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan di Query!");
            }
            setVisible(false);
            rsa.showDataPasien();
        } else {
            try{
                Statement stmt = koneksi.createStatement();
                String query = "UPDATE pasien SET nama_pasien = '"+nama
                +"', tempat_lahir = '"+tempat_lahir+"', tgl_lahir = '"+tgl_lahir+"', "
                + "alamat = '"+alamat+"', kota = '"+kota+"', telepon = '"+telp+"' WHERE nomedrec = '"+idpasien+"'";
                int berhasil = stmt.executeUpdate(query);
                if(berhasil == 1){
                    JOptionPane.showMessageDialog(null, "Data Berhasil Diubah!");
                } else {
                    JOptionPane.showMessageDialog(null, "Data Gagal Diubah!");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan di Query!");
            }
            setVisible(false);
            rsa.showDataPasien();
        }
    }//GEN-LAST:event_cmdSubmitActionPerformed

    private void tb_telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_telpActionPerformed

    private void tb_kotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_kotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_kotaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JTextField tb_alamat;
    private javax.swing.JTextField tb_kota;
    private javax.swing.JTextField tb_nama;
    private javax.swing.JTextField tb_nomedrec;
    private com.toedter.calendar.JDateChooser tb_tanggal;
    private javax.swing.JTextField tb_telp;
    private javax.swing.JTextField tb_tempat;
    // End of variables declaration//GEN-END:variables
}
