/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rumahsakit;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author Muhammad Ilham H
 */
public class ManageAlat extends javax.swing.JDialog {
    Connection koneksi;
    String action;
    public ManageAlat(java.awt.Frame parent, boolean modal, String act, String id_alat) {
        super(parent, modal);
        initComponents();
        koneksi = DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "rumahsakit");
        action = act;
        
        if (action.equals("edit")) {
            tb_id.setEnabled(false);
            showData(id_alat);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSimpan4 = new javax.swing.JButton();
        tb_nama = new javax.swing.JTextField();
        tb_id = new javax.swing.JTextField();
        txtJenis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tb_stok = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Stok");

        jLabel2.setText("Kode Alat");

        jLabel3.setText("Nama Alat");

        jLabel1.setFont(new java.awt.Font("Big Winks", 1, 36)); // NOI18N
        jLabel1.setText("Manage Data Alat");

        btnSimpan4.setText("Simpan");
        btnSimpan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan4ActionPerformed(evt);
            }
        });

        tb_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_idActionPerformed(evt);
            }
        });

        jLabel5.setText("Jenis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSimpan4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(58, 58, 58))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tb_stok)
                                .addComponent(tb_nama)
                                .addComponent(txtJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tb_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan4)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan4ActionPerformed
        RumahSakitApp rsa = new RumahSakitApp();

        if(action.equals("edit")) EditData();
        else SimpanData();

        rsa.showDataAlat();
        setVisible(false);
    }//GEN-LAST:event_btnSimpan4ActionPerformed

    private void tb_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_idActionPerformed

    public void SimpanData() {
        String kode = tb_id.getText();
        String nama = tb_nama.getText();
        String stok = String.valueOf(tb_stok.getValue());
        String jenis = txtJenis.getText();
        
        try {
            Statement stmt = koneksi.createStatement();
            String query = "INSERT INTO tbl_alat(id_alat,nama_alat,stok,jenis)"
                    + "VALUES('"+kode+"','"+nama+"','"+stok+"','"+jenis+"')";
            System.out.println(query
            );
            int berhasil = stmt.executeUpdate(query);
            if (berhasil == 1) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Dimasukkan");
            } else {
                JOptionPane.showMessageDialog(null, "Data Gagal Dimasukkan");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Pada Database");
        }
    }
    
     public void EditData() {
        String kode = tb_id.getText();
        String nama = tb_nama.getText();
        String stok = String.valueOf(tb_stok.getValue());
        String jenis = txtJenis.getText();
        
        try {
            Statement stmt = koneksi.createStatement();
            String query = "UPDATE tbl_alat SET id_alat = '"+kode+"',"
                    + "nama_alat = '"+nama+"',"
                    + "stok = '"+stok+"',"
            + "jenis = '"+jenis+"' WHERE id_alat = '"+kode+"'";
            System.out.println(query);
            int berhasil = stmt.executeUpdate(query);
            if(berhasil == 1) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            } else {
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
            }           
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Pada Query");
        }
    }
     
    void showData(String id_alat){
        try {
            Statement stmt = koneksi.createStatement();
            String query = "SELECT * FROM tbl_alat WHERE id_alat = '"+id_alat+"'";
            ResultSet rs = stmt.executeQuery(query);
            rs.first();
            tb_id.setText(rs.getString("id_alat"));
            tb_nama.setText(rs.getString("nama_alat"));
            tb_stok.setValue(new Integer(rs.getString("stok")));
            txtJenis.setText(rs.getString("jenis"));
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan di Query");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tb_id;
    private javax.swing.JTextField tb_nama;
    private javax.swing.JSpinner tb_stok;
    private javax.swing.JTextField txtJenis;
    // End of variables declaration//GEN-END:variables
}
